plugins:
  tslint:
    enabled: true
    config: frontend/tslint.json
  nodesecurity:
    enabled: true
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
  pmd:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  stylelint:
    enabled: true
    config: frontend/.stylelintrc.json
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
    - "**/*.java"
    - "**/*.ts"
    - "**/*.scss"
    - "**/*.md"
    - "**/*.sh"
    - "package.json"
    - "yarn.lock"

exclude_paths:
  - "./frontend/node_modules"
  - "./node_modules"
  - "./frontend/coverage"
  - "./frontend/dist"
  - "./backend/.mvn"
  - "./backend/src/test"
  - "./backend/src/**/*.{js,css,html}"
  - "./backend/.mvn/"
