coverage:
  precision: 2
  status:
    project: on
      default:
        target: 60%
    patch: on
      default:
        target: 60%
ignore:
  - "./backend/src/main/java/org/openhr/configuration/**/*.*"
  - "./backend/src/main/java/org/openhr/**/*Facade*.*"
