coverage:
  precision: 2
coverage:
  status:
    project: on
      default:
        target: 60%
    patch: on
      default:
        target: 60%
ignore:
  - "./backend/src/main/java/org/openhr/configuration/**/*"

