dist: trusty
sudo: false

language: node_js
node_js:
  - "6"
  - "8"

cache:
  directories:
     - ./node_modules

install:
  - cd frontend/
  - npm install

script:
  # Use Chromium instead of Chrome.
  - cd frontend
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox --code-coverage
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
