dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8
  - openjdk8

services:
  - mysql

env:
  - NODE_VERSION=node

cache:
  yarn: true
  directories:
     - ./frontend/node_modules
     - $HOME/.m2

matrix:
  fast_finish: true

ignore:
  - *.md
  - *.{jpg,png}

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3

before_install:
  - node --version
  - nvm install $NODE_VERSION
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g nsp
  - mysql -u root -e 'CREATE DATABASE openhr;'

install:
  - cd frontend/
  - yarn install
  - cd ../backend/
  - mvn install -B -D skipTests -e

script:
  - cd ../frontend/
  - npm run dist
  - xvfb-run -a npm run test -- --single-run --no-progress
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor.conf.js
  - nsp check
  - cd ../backend/
  - mvn package -B -D skipTests -e
  - mvn test -B -e
  
after_script:
  - mysql -u root -e 'DROP DATABASE openhr'

#after_success:
# - codecov

notifications:
  email: false
