@ECHO OFF

ECHO Creating target folder...
mkdir target
ECHO Navigating to frontend module...
cd ./frontend/
ECHO Downloading dependencies...
call npm install
ECHO Building frontend application...
call npm run dist
ECHO Build successful!
ECHO Moving files...
move dist/ ../target
ECHO Navigating to backend module...
cd ../backend
ECHO Installing dependencies...
./mvnw install
ECHO Building backend application...
./mvnw build
ECHO Build successful!
ECHO Done
ECHO _________________
