INSERT INTO LEAVE_TYPE (LEAVE_TYPE_ID, LEAVE_CATEGORY, DESCRIPTION) VALUES
  (1, 'Holiday', 'Paid annual leave'),
  (2, 'Maternity leave', '1 year maternity leave'),
  (3, 'Paternity leave', '1 year paternity leave'),
  (4, 'Sick day', 'Leave uncounted towards annual leave allowance'),
  (5, 'Unpaid leave', 'Unpaid leave uncounted towards annual leave allowance');
INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME, FLAG_URL) VALUES
  (1, 'Afghanistan', NULL),
  (2, 'Albania', NULL),
  (3, 'Algeria', NULL),
  (4, 'Andorra', NULL),
  (5, 'Angola', NULL),
  (6, 'Antigua & Deps', NULL),
  (7, 'Argentina', NULL),
  (8, 'Armenia', NULL),
  (9, 'Australia', NULL),
  (10, 'Austria', NULL),
  (11, 'Azerbaijan', NULL),
  (12, 'Bahamas', NULL),
  (13, 'Bahrain', NULL),
  (14, 'Bangladesh', NULL),
  (15, 'Barbados', NULL),
  (16, 'Belarus', NULL),
  (17, 'Belgium', NULL),
  (18, 'Belize', NULL),
  (19, 'Benin', NULL),
  (20, 'Bhutan', NULL),
  (21, 'Bolivia', NULL),
  (22, 'Bosnia Herzegovina', NULL),
  (23, 'Botswana', NULL),
  (24, 'Brazil', NULL),
  (25, 'Brunei', NULL),
  (26, 'Bulgaria', NULL),
  (27, 'Burkina', NULL),
  (28, 'Burundi', NULL),
  (29, 'Cambodia', NULL),
  (30, 'Cameroon', NULL),
  (31, 'Canada', NULL),
  (32, 'Cape Verde', NULL),
  (33, 'Central African Rep', NULL),
  (34, 'Chad', NULL),
  (35, 'Chile', NULL),
  (36, 'China', NULL),
  (37, 'Colombia', NULL),
  (38, 'Comoros', NULL),
  (39, 'Congo', NULL),
  (40, 'Congo {Democratic Rep}', NULL),
  (41, 'Costa Rica', NULL),
  (42, 'Croatia', NULL),
  (43, 'Cuba', NULL),
  (44, 'Cyprus', NULL),
  (45, 'Czech Republic', NULL),
  (46, 'Denmark', NULL),
  (47, 'Djibouti', NULL),
  (48, 'Dominica', NULL),
  (49, 'Dominican Republic', NULL),
  (50, 'East Timor', NULL),
  (51, 'Ecuador', NULL),
  (52, 'Egypt', NULL),
  (53, 'El Salvador', NULL),
  (54, 'Equatorial Guinea', NULL),
  (55, 'Eritrea', NULL),
  (56, 'Estonia', NULL),
  (57, 'Ethiopia', NULL),
  (58, 'Fiji', NULL),
  (59, 'Finland', NULL),
  (60, 'France', NULL),
  (61, 'Gabon', NULL),
  (62, 'Gambia', NULL),
  (63, 'Georgia', NULL),
  (64, 'Germany', NULL),
  (65, 'Ghana', NULL),
  (66, 'Greece', NULL),
  (67, 'Grenada', NULL),
  (68, 'Guatemala', NULL),
  (69, 'Guinea', NULL),
  (70, 'Guinea-Bissau', NULL),
  (71, 'Guyana', NULL),
  (72, 'Haiti', NULL),
  (73, 'Honduras', NULL),
  (74, 'Hungary', NULL),
  (75, 'Iceland', NULL),
  (76, 'India', NULL),
  (77, 'Indonesia', NULL),
  (78, 'Iran', NULL),
  (79, 'Iraq', NULL),
  (80, 'Ireland {Republic}', NULL),
  (81, 'Israel', NULL),
  (82, 'Italy', NULL),
  (83, 'Ivory Coast', NULL),
  (84, 'Jamaica', NULL),
  (85, 'Japan', NULL),
  (86, 'Jordan', NULL),
  (87, 'Kazakhstan', NULL),
  (88, 'Kenya', NULL),
  (89, 'Kiribati', NULL),
  (90, 'Korea North', NULL),
  (91, 'Korea South', NULL),
  (92, 'Kosovo', NULL),
  (93, 'Kuwait', NULL),
  (94, 'Kyrgyzstan', NULL),
  (95, 'Laos', NULL),
  (96, 'Latvia', NULL),
  (97, 'Lebanon', NULL),
  (98, 'Lesotho', NULL),
  (99, 'Liberia', NULL),
  (100, 'Libya', NULL),
  (101, 'Liechtenstein', NULL),
  (102, 'Lithuania', NULL),
  (103, 'Luxembourg', NULL),
  (104, 'Macedonia', NULL),
  (105, 'Madagascar', NULL),
  (106, 'Malawi', NULL),
  (107, 'Malaysia', NULL),
  (108, 'Maldives', NULL),
  (109, 'Mali', NULL),
  (110, 'Malta', NULL),
  (111, 'Marshall Islands', NULL),
  (112, 'Mauritania', NULL),
  (113, 'Mauritius', NULL),
  (114, 'Mexico', NULL),
  (115, 'Micronesia', NULL),
  (116, 'Moldova', NULL),
  (117, 'Monaco', NULL),
  (118, 'Mongolia', NULL),
  (119, 'Montenegro', NULL),
  (120, 'Morocco', NULL),
  (121, 'Mozambique', NULL),
  (122, 'Myanmar, {Burma}', NULL),
  (123, 'Namibia', NULL),
  (124, 'Nauru', NULL),
  (125, 'Nepal', NULL),
  (126, 'Netherlands', NULL),
  (127, 'New Zealand', NULL),
  (128, 'Nicaragua', NULL),
  (129, 'Niger', NULL),
  (130, 'Nigeria', NULL),
  (131, 'Norway', NULL),
  (132, 'Oman', NULL),
  (133, 'Pakistan', NULL),
  (134, 'Palau', NULL),
  (135, 'Panama', NULL),
  (136, 'Papua New Guinea', NULL),
  (137, 'Paraguay', NULL),
  (138, 'Peru', NULL),
  (139, 'Philippines', NULL),
  (140, 'Poland', NULL),
  (141, 'Portugal', NULL),
  (142, 'Qatar', NULL),
  (143, 'Romania', NULL),
  (144, 'Russian Federation', NULL),
  (145, 'Rwanda', NULL),
  (146, 'St Kitts & Nevis', NULL),
  (147, 'St Lucia', NULL),
  (148, 'Saint Vincent & the Grenadines', NULL),
  (149, 'Samoa', NULL),
  (150, 'San Marino', NULL),
  (151, 'Sao Tome & Principe', NULL),
  (152, 'Saudi Arabia', NULL),
  (153, 'Senegal', NULL),
  (154, 'Serbia', NULL),
  (155, 'Seychelles', NULL),
  (156, 'Sierra Leone', NULL),
  (157, 'Singapore', NULL),
  (158, 'Slovakia', NULL),
  (159, 'Slovenia', NULL),
  (160, 'Solomon Islands', NULL),
  (161, 'Somalia', NULL),
  (162, 'South Africa', NULL),
  (163, 'South Sudan', NULL),
  (164, 'Spain', NULL),
  (165, 'Sri Lanka', NULL),
  (166, 'Sudan', NULL),
  (167, 'Suriname', NULL),
  (168, 'Swaziland', NULL),
  (169, 'Sweden', NULL),
  (170, 'Switzerland', NULL),
  (171, 'Syria', NULL),
  (172, 'Taiwan', NULL),
  (173, 'Tajikistan', NULL),
  (174, 'Tanzania', NULL),
  (175, 'Thailand', NULL),
  (176, 'Togo', NULL),
  (177, 'Tonga', NULL),
  (178, 'Trinidad & Tobago', NULL),
  (179, 'Tunisia', NULL),
  (180, 'Turkey', NULL),
  (181, 'Turkmenistan', NULL),
  (182, 'Tuvalu', NULL),
  (183, 'Uganda', NULL),
  (184, 'Ukraine', NULL),
  (185, 'United Arab Emirates', NULL),
  (186, 'United Kingdom', NULL),
  (187, 'United States', NULL),
  (188, 'Uruguay', NULL),
  (189, 'Uzbekistan', NULL),
  (190, 'Vanuatu', NULL),
  (191, 'Vatican City', NULL),
  (192, 'Venezuela', NULL),
  (193, 'Vietnam', NULL),
  (194, 'Yemen', NULL),
  (195, 'Zambia', NULL),
  (196, 'Zimbabwe', NULL);

INSERT INTO ALLOWANCE_SETTINGS (ID, AUTO_RESET_ALLOWANCE, RESET_DATE, CARRY_OVER_UNUSED_LEAVE, NUMBER_OF_DAYS_TO_CARRY_OVER) VALUES
  (1, 'F', NULL, 'F', 0);

# First user with all privileges
SET FOREIGN_KEY_CHECKS=0;
INSERT INTO CONTACT_INFORMATION (CONTACT_INFORMATION_ID, CITY, COUNTRY, FIRST_LINE_ADDRESS, POSTCODE, SECOND_LINE_ADDRESS,
                                 THIRD_LINE_ADDRESS, EMAIL, TELEPHONE) VALUES
  (1, '', '', '', '', '', '', '', '');
INSERT INTO EMPLOYEE_INFORMATION (EMPLOYEE_INFORMATION_ID, DEPARTMENT, EMPLOYEE_NUMBER, END_DATE, NATIONAL_INSURANCE_NUMBER,
                                  POSITION, START_DATE) VALUES
  (1, '', '', NULL, '', '', NULL);
INSERT INTO HR_INFORMATION (HR_INFORMATION_ID, ALLOWANCE, USED_ALLOWANCE) VALUES
  (1, 25, 0);
INSERT INTO PERSONAL_INFORMATION (PERSONAL_INFORMATION_ID, DATE_OF_BIRTH, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES
  (1, NULL, 'HR', 'Account', NULL);
INSERT INTO USER (ID, NOTIFICATIONS, PASSWORD, USERNAME) VALUES
  (1, 'Y', '$2a$08$xWAlCYTDDhrOdaoeP8L4o.uRadyo2U4vltbMxVDJ8Zaxz72JjfSbG', 'hr');
INSERT INTO USER_ROLE (USER_ROLE_ID, USER_ROLE, USER_ID) VALUES
  (1, 'HRTEAMMEMBER', 1);
INSERT INTO HR_TEAM_MEMBER (SUBJECT_ID, ROLE, CONTACT_INFORMATION_ID, EMPLOYEE_INFORMATION_ID, HR_INFORMATION_ID,
                            PERSONAL_INFORMATION_ID, USER_ID) VALUES
  (1, 'HRTEAMMEMBER', 1, 1, 1, 1, 1);
SET FOREIGN_KEY_CHECKS=1;

DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
DROP TABLE IF EXISTS QRTZ_LOCKS;
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
DROP TABLE IF EXISTS QRTZ_CALENDARS;

CREATE TABLE QRTZ_JOB_DETAILS(
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  JOB_CLASS_NAME VARCHAR(250) NOT NULL,
  IS_DURABLE BOOLEAN NOT NULL,
  IS_NONCONCURRENT BOOLEAN NOT NULL,
  IS_UPDATE_DATA BOOLEAN NOT NULL,
  REQUESTS_RECOVERY BOOLEAN NOT NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  NEXT_FIRE_TIME BIGINT(19) NULL,
  PREV_FIRE_TIME BIGINT(19) NULL,
  PRIORITY INTEGER NULL,
  TRIGGER_STATE VARCHAR(16) NOT NULL,
  TRIGGER_TYPE VARCHAR(8) NOT NULL,
  START_TIME BIGINT(19) NOT NULL,
  END_TIME BIGINT(19) NULL,
  CALENDAR_NAME VARCHAR(200) NULL,
  MISFIRE_INSTR SMALLINT(2) NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
  REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  REPEAT_COUNT BIGINT(7) NOT NULL,
  REPEAT_INTERVAL BIGINT(12) NOT NULL,
  TIMES_TRIGGERED BIGINT(10) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  CRON_EXPRESSION VARCHAR(120) NOT NULL,
  TIME_ZONE_ID VARCHAR(80),
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_SIMPROP_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  STR_PROP_1 VARCHAR(512) NULL,
  STR_PROP_2 VARCHAR(512) NULL,
  STR_PROP_3 VARCHAR(512) NULL,
  INT_PROP_1 INT NULL,
  INT_PROP_2 INT NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC(13,4) NULL,
  DEC_PROP_2 NUMERIC(13,4) NULL,
  BOOL_PROP_1 BOOLEAN NULL,
  BOOL_PROP_2 BOOLEAN NULL,
  TIME_ZONE_ID VARCHAR(80) NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_BLOB_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  BLOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  INDEX (SCHED_NAME,TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME VARCHAR(200) NOT NULL,
  CALENDAR BLOB NOT NULL,
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_FIRED_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR(140) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  FIRED_TIME BIGINT(19) NOT NULL,
  SCHED_TIME BIGINT(19) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE VARCHAR(16) NOT NULL,
  JOB_NAME VARCHAR(200) NULL,
  JOB_GROUP VARCHAR(200) NULL,
  IS_NONCONCURRENT BOOLEAN NULL,
  REQUESTS_RECOVERY BOOLEAN NULL,
  PRIMARY KEY (SCHED_NAME,ENTRY_ID))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME BIGINT(19) NOT NULL,
  CHECKIN_INTERVAL BIGINT(19) NOT NULL,
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME))
  ENGINE=InnoDB;

CREATE TABLE QRTZ_LOCKS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  LOCK_NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY (SCHED_NAME,LOCK_NAME))
  ENGINE=InnoDB;

CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(SCHED_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS(SCHED_NAME,JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME,CALENDAR_NAME);
CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME);
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);

commit;
