INSERT INTO LEAVE_TYPE (LEAVE_TYPE_ID, LEAVE_CATEGORY, DESCRIPTION) VALUES
  (1, 'Holiday', 'Paid annual leave'),
  (2, 'Maternity leave', '1 year maternity leave'),
  (3, 'Paternity leave', '1 year paternity leave'),
  (4, 'Sick day', 'Leave uncounted towards annual leave allowance'),
  (5, 'Unpaid leave', 'Unpaid leave uncounted towards annual leave allowance');
INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME, FLAG_URL) VALUES
  (1, 'Afghanistan', null),
  (2, 'Albania', null),
  (3, 'Algeria', null),
  (4, 'Andorra', null),
  (5, 'Angola', null),
  (6, 'Antigua & Deps', null),
  (7, 'Argentina', null),
  (8, 'Armenia', null),
  (9, 'Australia', null),
  (10, 'Austria', null),
  (11, 'Azerbaijan', null),
  (12, 'Bahamas', null),
  (13, 'Bahrain', null),
  (14, 'Bangladesh', null),
  (15, 'Barbados', null),
  (16, 'Belarus', null),
  (17, 'Belgium', null),
  (18, 'Belize', null),
  (19, 'Benin', null),
  (20, 'Bhutan', null),
  (21, 'Bolivia', null),
  (22, 'Bosnia Herzegovina', null),
  (23, 'Botswana', null),
  (24, 'Brazil', null),
  (25, 'Brunei', null),
  (26, 'Bulgaria', null),
  (27, 'Burkina', null),
  (28, 'Burundi', null),
  (29, 'Cambodia', null),
  (30, 'Cameroon', null),
  (31, 'Canada', null),
  (32, 'Cape Verde', null),
  (33, 'Central African Rep', null),
  (34, 'Chad', null),
  (35, 'Chile', null),
  (36, 'China', null),
  (37, 'Colombia', null),
  (38, 'Comoros', null),
  (39, 'Congo', null),
  (40, 'Congo {Democratic Rep}', null),
  (41, 'Costa Rica', null),
  (42, 'Croatia', null),
  (43, 'Cuba', null),
  (44, 'Cyprus', null),
  (45, 'Czech Republic', null),
  (46, 'Denmark', null),
  (47, 'Djibouti', null),
  (48, 'Dominica', null),
  (49, 'Dominican Republic', null),
  (50, 'East Timor', null),
  (51, 'Ecuador', null),
  (52, 'Egypt', null),
  (53, 'El Salvador', null),
  (54, 'Equatorial Guinea', null),
  (55, 'Eritrea', null),
  (56, 'Estonia', null),
  (57, 'Ethiopia', null),
  (58, 'Fiji', null),
  (59, 'Finland', null),
  (60, 'France', null),
  (61, 'Gabon', null),
  (62, 'Gambia', null),
  (63, 'Georgia', null),
  (64, 'Germany', null),
  (65, 'Ghana', null),
  (66, 'Greece', null),
  (67, 'Grenada', null),
  (68, 'Guatemala', null),
  (69, 'Guinea', null),
  (70, 'Guinea-Bissau', null),
  (71, 'Guyana', null),
  (72, 'Haiti', null),
  (73, 'Honduras', null),
  (74, 'Hungary', null),
  (75, 'Iceland', null),
  (76, 'India', null),
  (77, 'Indonesia', null),
  (78, 'Iran', null),
  (79, 'Iraq', null),
  (80, 'Ireland {Republic}', null),
  (81, 'Israel', null),
  (82, 'Italy', null),
  (83, 'Ivory Coast', null),
  (84, 'Jamaica', null),
  (85, 'Japan', null),
  (86, 'Jordan', null),
  (87, 'Kazakhstan', null),
  (88, 'Kenya', null),
  (89, 'Kiribati', null),
  (90, 'Korea North', null),
  (91, 'Korea South', null),
  (92, 'Kosovo', null),
  (93, 'Kuwait', null),
  (94, 'Kyrgyzstan', null),
  (95, 'Laos', null),
  (96, 'Latvia', null),
  (97, 'Lebanon', null),
  (98, 'Lesotho', null),
  (99, 'Liberia', null),
  (100, 'Libya', null),
  (101, 'Liechtenstein', null),
  (102, 'Lithuania', null),
  (103, 'Luxembourg', null),
  (104, 'Macedonia', null),
  (105, 'Madagascar', null),
  (106, 'Malawi', null),
  (107, 'Malaysia', null),
  (108, 'Maldives', null),
  (109, 'Mali', null),
  (110, 'Malta', null),
  (111, 'Marshall Islands', null),
  (112, 'Mauritania', null),
  (113, 'Mauritius', null),
  (114, 'Mexico', null),
  (115, 'Micronesia', null),
  (116, 'Moldova', null),
  (117, 'Monaco', null),
  (118, 'Mongolia', null),
  (119, 'Montenegro', null),
  (120, 'Morocco', null),
  (121, 'Mozambique', null),
  (122, 'Myanmar, {Burma}', null),
  (123, 'Namibia', null),
  (124, 'Nauru', null),
  (125, 'Nepal', null),
  (126, 'Netherlands', null),
  (127, 'New Zealand', null),
  (128, 'Nicaragua', null),
  (129, 'Niger', null),
  (130, 'Nigeria', null),
  (131, 'Norway', null),
  (132, 'Oman', null),
  (133, 'Pakistan', null),
  (134, 'Palau', null),
  (135, 'Panama', null),
  (136, 'Papua New Guinea', null),
  (137, 'Paraguay', null),
  (138, 'Peru', null),
  (139, 'Philippines', null),
  (140, 'Poland', null),
  (141, 'Portugal', null),
  (142, 'Qatar', null),
  (143, 'Romania', null),
  (144, 'Russian Federation', null),
  (145, 'Rwanda', null),
  (146, 'St Kitts & Nevis', null),
  (147, 'St Lucia', null),
  (148, 'Saint Vincent & the Grenadines', null),
  (149, 'Samoa', null),
  (150, 'San Marino', null),
  (151, 'Sao Tome & Principe', null),
  (152, 'Saudi Arabia', null),
  (153, 'Senegal', null),
  (154, 'Serbia', null),
  (155, 'Seychelles', null),
  (156, 'Sierra Leone', null),
  (157, 'Singapore', null),
  (158, 'Slovakia', null),
  (159, 'Slovenia', null),
  (160, 'Solomon Islands', null),
  (161, 'Somalia', null),
  (162, 'South Africa', null),
  (163, 'South Sudan', null),
  (164, 'Spain', null),
  (165, 'Sri Lanka', null),
  (166, 'Sudan', null),
  (167, 'Suriname', null),
  (168, 'Swaziland', null),
  (169, 'Sweden', null),
  (170, 'Switzerland', null),
  (171, 'Syria', null),
  (172, 'Taiwan', null),
  (173, 'Tajikistan', null),
  (174, 'Tanzania', null),
  (175, 'Thailand', null),
  (176, 'Togo', null),
  (177, 'Tonga', null),
  (178, 'Trinidad & Tobago', null),
  (179, 'Tunisia', null),
  (180, 'Turkey', null),
  (181, 'Turkmenistan', null),
  (182, 'Tuvalu', null),
  (183, 'Uganda', null),
  (184, 'Ukraine', null),
  (185, 'United Arab Emirates', null),
  (186, 'United Kingdom', null),
  (187, 'United States', null),
  (188, 'Uruguay', null),
  (189, 'Uzbekistan', null),
  (190, 'Vanuatu', null),
  (191, 'Vatican City', null),
  (192, 'Venezuela', null),
  (193, 'Vietnam', null),
  (194, 'Yemen', null),
  (195, 'Zambia', null),
  (196, 'Zimbabwe', null);
